### ISSUE TITLE
Loaders smoke tests on real content

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#10]
**Blocked by https://github.com/hplush/slowreader/issues/96**

In `loader-tests/` we need to create a config with URLs to test loaders on real data.

- [ ] Add script file and `integration` script to project’s `package.json`. It will use a lot from #96, think about code re-using.
- [ ] This script need to read `loader-tests/feeds.yml`
- [ ] Add there `dev.to`, LiveJournal, Tumblr (some safe-for-work project, ideal the artist with their work), WordPress official blog, other blog engines blogs, some popular blogs you know (Github).
- [ ] For each RSS try to find the right loader by calling `loader.isMineText()`. Show nice error if the loader was not found.
- [ ] For found loader call `loader.getMineLinksFromText()`. Be sure that it returned some posts.
- [ ] For URL remove path (`https://example.com/news.rss` → `https://example.com/`) and call use methods from `core/preview.ts` to be sure that reader will find that RSS URL from the home. `feeds.yml` should have a marker to disable this test for feed.
- [ ] Add to docs information about that test and that file.
- [ ] Add CI workflow to run that script every day.

**Comment by ilyatitovich** [comment]
Can I take it?

**Comment by ai** [comment]
Sure! BTW, check `load-tests/check-opml.ts`. We need very close to it, just with a different config (OPML is limited for RSS).
