### ISSUE TITLE
Replace `picocolors` to `util.styleText`

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#117]
Upcoming Node.js 20.12 will have built-in function for color output: [`util.styleText`](https://nodejs.org/en/blog/release/v20.12.0#text-styling)

1. Replace `picocolors` in our scripts, etc.
2. Remove `picocolors` dependency.

**Comment by Edward-Leopold** [comment]
I want to take it

**Comment by ai** [comment]
@Edward-Leopold don’t forget to create PR tomorrow or give task to another people
