### ISSUE TITLE
Define styles for all post’s tag 

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#118]
We have XSS protection for post’s body and define allow-list of [all possible tags](https://github.com/hplush/slowreader/blob/main/core/html.ts#L3) in post.

We need to add base styles for that tags and check them in Storybook.

- [ ] Add styles to `web/ui/formatted-text.svelte`.
- [ ] Add `web/ui/stories/ui/formatted-text.stories.svelte` story with all possible cases. Try to use the single `<Story>` (we are on the free plan in Chromatic with snapshots limits 🥲)

**Comment by upteran** [comment]
Hi, I want to take it

**Comment by ai** [comment]
Sure. It is your.

**Comment by ai** [comment]
@upteran I moved task back to Onboarding. You still can create a PR, but the task is not locked to you now.

**Comment by upteran** [comment]
@ai sry loaded week, I just wanted to send this today. I've created a PR with few questions
