### ISSUE TITLE
Add post during subscribing to the feed

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#122]
Now, when you subscribe to the feed you will not see the new feed in Slow/Fast section (because there are no posts after subscription to the feed).

Let’s add the latest post from the new feed.

- [ ] Change `addPreviewCandidate()` in `core/preview.ts` by adding post adding code from [`core/refresh`](https://github.com/hplush/slowreader/blob/main/core/refresh.ts#L109-L124).
- [ ] Find a way to re-use post adding code between `core/preview.ts` and `core/refresh`. For instance, by creating some helper in `core/post.ts`.
- [ ] Add tests

**Comment by Konfuze** [comment]
would like to implement it if you don't mind

**Comment by ai** [comment]
@Konfuze you already onboarded :) We have a little shortage of Onboarding task and let’s keep them for new developers.

**Comment by Konfuze** [comment]
ah, okay! i'll find something else :)

**Comment by chafilin** [comment]
Hello! I want to take it

**Comment by ai** [comment]
It is your 👍
