### ISSUE TITLE
Add pagination to Slow

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#136]
Right now having `slow` feeds with 100+ posts freeze browser when you open them.

So we need to add pagination. Requirements:
1. As with pagination in `fast` we need to keep the current page in URL.
2. Adding new posts should not change posts in pages. So it is better to use `since` rather than `page` in URL.
3. In contrast with pagination in `fast` user need to see how many pages are in the list.
4. Users need not only `next page`, but also the last page link, etc.
5. The small `1, 2, 3` links are not very useful. We need something better in terms of UX.

**Comment by pekac** [comment]
If it's ok, I'd like to take this one :grin:

**Comment by pekac** [comment]
In terms of UX, does something like this make sense?

![Image](https://github.com/hplush/slowreader/assets/7286321/c651b5d9-3b26-460a-8e26-8647216135cd)

**Comment by ai** [comment]
@pekac `>`/`>>` graphic language is not clear for most of the people.

I will ask my friends from design team for advice.

**Comment by ai** [comment]
After internal discussion we decided for something like progressbar

```
[----+++---------] 400 posts
[Next page]
```

and you can click in the area of progress bar

**Comment by ai** [comment]
The next step https://github.com/hplush/slowreader/issues/152
