### ISSUE TITLE
Add more Markdown plugins

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#140]
The second step of #97 task after #129.

We need to add a few custom Remark plugins.

- [x] That TOC has right titles and URLs.
- [x] That titles have the correct word's capitalization (a/the is small, noun is starting from big latter).
- [ ] That file use curvy typography "→”, '→’.
- [x] That code block inside list do not split the list (has the right indent)

We can release those Remark plugins as open source project (or do it as internal plugins).

**Comment by ilyatitovich** [comment]
I'd like to take it. I think it would be cool to release plugins as open source projects.
