### ISSUE TITLE
Search for feeds in HTML

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#141]
Some web pages don’t use proper `<link>` tag to their RSS channel.

Instead, they just have `<a>` link.

We need to add to RSS/Atom loader in `core/loaders` small heuristics to search some of the links.

We can use:
1. Link has `feed.` in domain
2. Link has filename `feed.xml`
3. Link has `.rss`, `.atom` extensions
4. Link has `/rss` or `/atom` path

Of course, we will need tests for that.

**Comment by sanchopanda** [comment]
I want to take task

**Comment by ai** [comment]
Sure, it is your
