### ISSUE TITLE
Add progress to Check OPML script

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#143]
We have `loader-tests/check-opml.ts` script to check feeds from OPML file. You can run it by:

```sh
pnpm check-opml ./loader-tests/example.ompl
```

We want to add progress bar to the process like:

```
███████████░░░░░
```

In `loader-tests` we plan to have many scripts, so this progress bar should re-usable from `loader-tests/utils.ts`. For instance:
1. In the start script define jobs number by `setJobs(number)`
2. On every `success()`/`error()` call we mark next job as completed.

We should not show progress on CI.

**Comment by ai** [comment]
The good article for this task: https://evilmartians.com/chronicles/cli-ux-best-practices-3-patterns-for-improving-progress-displays

**Comment by Kamino0** [comment]
Do I understand correctly that we do not want change the current logs to the console and just always draw the bar on the last line?

In this case, I see only one solution. Correct me if I'm thinking in the wrong direction

First, we draw an empty progress bar and each time we move through the jobs, we delete the last line and draw bar again with a new state.
But there is one complication -- other logs will be in last line, that we want delete, not progress bar. Everything seems to be easy with the logs that are written to loader-tests/utils.ts -- you can slightly update the print function
```
export function print(msg: string): void {
   // remove last line
   process.stderr.write(`${msg}\n`)
   // draw the bar
}
```
But what to do with those in @slowreader/core?
Should I rewrite the console.log for the entire project or create a wrapper similar to print from loader-tests/utils.ts?
I don't like any of this ideas

Also there typo in extension
`pnpm check-opml ./loader-tests/example.ompl`
should be
`pnpm check-opml ./loader-tests/example.opml`

**Comment by ai** [comment]
> Do I understand correctly that we do not want change the current logs to the console and just always draw the bar on the last line?

Yes

> you can slightly update the print function

Good idea, I missed that problem

> Should I rewrite the console.log for the entire project or create a wrapper similar to print from loader-tests/utils.ts?
I don't like any of this ideas

Just fix `print()` in `loader-tests/utils.ts`. It is just a local fun in loader tests CLI tools.

**Comment by Kamino0** [comment]
> I missed that problem

I'm getting an error: `JSON feed field 'items' is not valid with value undefined`. It looks like it was generated in the [core](https://github.com/hplush/slowreader/blob/main/core/loader/json-feed.ts#L92). Therefore, simply updating the `print()` function will not be enough. And there could potentially be more logs like that.

**Comment by ai** [comment]
It is just a warning, you can ignore it.

**Comment by Kamino0** [comment]
Looks like I cannot ignore it. I'm getting strings that are not deleted correctly due to warnings like this because my solution is not designed for writing to the console that happens not from utils.
```
...
✓ Feed AppSignal has feed URL at home
✓ Feed Fabien Sanglard has feed URL at home
[█████████░░░░░░░░░░░] 46.67% // Incorrect. Should be deleted. But deleted was external warning.
✓ Feed Farnam Street has feed URL at home
✓ Feed Ferd.ca has feed URL at home
[███████████░░░░░░░░░] 56.67% // Correct bar
```

**Comment by ai** [comment]
I will hide it today or tomorrow.

BTW, let’s remove `[` and `]` and use the full width. We can even ignore `%` if they do not provide extra information.
