### ISSUE TITLE
Error when trying to change feed's type

### ISSUE THREAD

**Issue by pekac** [hplush/slowreader#148]
Error when trying to change feed's type from "slow" to "fast" from the categories page.

Steps to reproduce:
1. Go to categories page
2. Find a feed that is currently marked as "slow" and has unread posts
3. Change feed's type to "fast"
4. Go to "fast posts" page
5. Feed's posts can not be found on "fast posts" page

Result: 
- Feed's posts not found on "fast posts" page
- Feed found on "slow posts" page

Expected result:
- Feed's posts are visible on "fast posts" page
- Feed should not be visible on "slow posts" page

Video for more info:
![changing-feed-type-crop](https://github.com/hplush/slowreader/assets/7286321/8568eade-4a4f-4aa8-9cf6-ddf13cb9cb23)

**Comment by ai** [comment]
It is more UX issue.

Adding a new filter or changing the category will not move previous posts. The main problem is filters.

Maybe we can load all current posts and change their type on every feed type or filter changes.

**Comment by chafilin** [comment]
I want to take task
