### ISSUE TITLE
Add better UI for slow posts pagination

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#152]
On slow pages we need:

1. An ability to see how many unread posts do we have in total (in this feed).
2. An ability to quickly go to the end and start reading from the end to beginning.
3. An ability to quickly navigate between pages, for instance, to find some posts which should be somewhere in the between.

After discussions in https://github.com/hplush/slowreader/issues/136 we are thinking about progressbar UI like:

```
[----+++---------] 400 posts
[Next page]
```

In progressbar we highlight the current page position and also user can click on any part of slider.

The interesting problem of the task, is that current `since` could not be aligned with `total_unread_posts / per_page`.

**Comment by pekac** [comment]
@ai , I'd like to take it if it's ok :)
