### ISSUE TITLE
Add Import and Export pages

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#177]
This task is too adding the core feature, without a design (I will do it myself later).

We need to support formats:
- OPML. Only for `atom`/`rss`/`json-feed`.
- Internal format. JSON file with `feeds`, `posts`, keys. The format will contain the full state of `feeds` including `lastOriginId`, `lastPublishedAt`, etc. We will use this format for debug and to backup the app state.

- [ ] Add Import and Export pages to `Manage Feeds` settings section.
- [ ] Add export page
  1. On first step user need to choose the format OPML/Internal.
  2. On the second for OPML user will see `All feeds`/`Select feeds` radio
  3. On selecting `Select feeds` user will see all feeds on the same page (by categories) with checkboxes (and checkbox for category). Also buttons to Select all and Unselect all.
  4. Then we need a loader on the file generation process
  5. And then browser will suggest user to save file
  6. If user, select internal format, we will ask him `All posts`/`No posts`, `All feeds`/`Select feeds`. Then the feeds selection if necessary.
- [ ] Add import page
  1. On the page user will see only `type=file` control.
  2. After selecting the file, we will ask what feeds user want to import from the file (the same `all`/`select` and list of feeds)
  3. Then we may need some loader (use `starting` store for now, because we will need to hide menu) for the import process

All feeds selection, import/export logic should be done in `core/`. In `web/` we just connect stores/methods to Web API.

**Comment by sanchopanda** [comment]
I'd like to try to do this task
