### ISSUE TITLE
Do not show mobile menu on no categories

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#178]
On mobile, we show posts list after clicking on Fast/Slow buttons.

We need to close that menu if the list is empty of contains only 1 element (like 1 category for Fast or 1 feed for Slow).

Note, that Fast/Slow menus is loading the data and is not ready when user click on the menu. So it is better to use `core` API to check the categories. You may create some helpers (so we will re-use them in mobile client).

**Comment by ilyatitovich** [comment]
I want to take it
