### ISSUE TITLE
Add visual tests for Slow/Fast page

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#179]
We need Storybook stories for Slow and Fast posts.

What cases we need to cover:
1. 3 posts on the page
2. Many posts so we have a pagination
3. Case 1, but some post is open

The problem is that we can’t use `lorem ipsum` and other random text.

We need some real posts. I suggest using [Wiki news](https://en.wikinews.org/wiki/Main_Page) (something neutral, like science news).

**Comment by baileys-li** [comment]
I want to take it

**Comment by ai** [comment]
It is your

**Comment by ai** [comment]
@baileys-li can I move task back to `Ready to Take`?

**Comment by ai** [comment]
Hm, maybe it is a good idea to create Docker for the project development. 

You are not the first one who straggle with conflict between Node version managers.

**Comment by ai** [comment]
Warnings were hidden https://github.com/hplush/slowreader/commit/8cf2df8137ad208af74c57e62427ef813ad1000c
