### ISSUE TITLE
Add desktop support for going back from the steps

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#197]
We have `<TwoStepPage>` and the logic to move back in those steps [for mobile](https://github.com/hplush/slowreader/pull/186).

We need to add the same back logic to desktop cases:

1. We need to add some header to second step with `×` button. We should not show this header on mobile.
2. We should check that `Escape` works as expected and also closes second step. We need to be sure, that it doesn’t have conflict with `keyux` jumps.
   1. We need to test all 3 cases: Slow posts, Feed add, Feed categories
   2. We need to test Esc after keyboard interactions (hotkeys, arrows, Enter) and after the mouse clicks

**Comment by ilyatitovich** [comment]
I want to take it
