### ISSUE TITLE
Add candidate to preview URL

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#201]
We do not keep the current selected candidate in `/feeds/add` URL.

Let’s add it. It will simplify the `two-page` logic a lot since we will not have route-less back logic.

- [ ] Add `candidate` to `core/router.ts`
- [ ] Add route to `web/stores/router.ts`
- [ ] Change `core/preview.ts` to use router
- [ ] Change web client to use links instead of buttons on Add Feed page

**Comment by ilyatitovich** [comment]
I want to take it

**Comment by ai** [comment]
Sure!
