### ISSUE TITLE
Add botton gutter to the mobile layout

### ISSUE THREAD

**Issue by BANOnotIT** [hplush/slowreader#233]
When the feed list on Import page is long enough "Import" button is hidden under the application menu.

![image](https://github.com/user-attachments/assets/bfb9073a-b6d6-4b6c-badb-fdb8d0583752)

**Comment by ai** [comment]
Can you give me you browser?

I can’t reproduce it in simple case.

**Comment by BANOnotIT** [comment]
FF Android 128.0.1

But I tried now and I was able to scroll further and see the Import button... So I can't reproduce it even myself.

**Comment by ai** [comment]
Maybe I fixed one relative thing recently.

Thanks for reporting.
