### ISSUE TITLE
Add option to download article’s content for offline usage

### ISSUE THREAD

**Issue by 3timeslazy** [hplush/slowreader#243]
Hi there,

I think it would be cool to be able to add a button or something to download the article so that it can be read offline.

**Comment by ai** [comment]
Of course! Must have feature (but I plat to implement it only when we will have working prototype).

We have another issue for that, so I am closing this one:
https://github.com/hplush/slowreader/issues/54

**Comment by 3timeslazy** [comment]
Thanks! 

I read the issue and it didn't mention offline capabilities at all, so I'd suggest adding something like "Once the post marked as 'Read Later' it should be downloaded for offline use". This will prevent other people from making duplicate issues like mine.

Also, I don't what's the right name for that (PWA?), but it would be nice to get the reader, when it's added to the home screen, to look like a native app with browser's interface. Could you please tell me if there is such a feature request already?

**Comment by ai** [comment]
We have offline out-of-the-box because of local-first architecture.

Everything in UI is offline ready.

**Comment by ai** [comment]
We are planning:

1. Have PWA first
2. Then create native app with React Native when we have resources (this is why we move all logic to the core, to make it easier to create native clients)

**Comment by 3timeslazy** [comment]
> We have offline out-of-the-box because of local-first architecture.
> Everything in UI is offline ready.

Sure, I understand that. What I wanted to say is that right now it's not a PWA and if I turn off the internet it won't work, unlike [js13kpwa](https://mdn.github.io/pwa-examples/js13kpwa/) as an example

**Comment by ai** [comment]
Yes, it is planned for the future since we need to find the best update strategy (when we will use cache issues of network and when revalidate cache).

All PWA cache strategies is far to be perfect, so we need a good research.

If you want, you can join this task. I can explain the problem with PWA cache strategies in [my Telegram](https://t.me/sitnik)
