### ISSUE TITLE
Add `xml:base` to Atom loader

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#57]
Add [`xml:base`](https://www.w3.org/TR/xmlbase/) to link resolution in Atom loader.

Check the same attribute for RSS.

**Comment by pekac** [comment]
I want to take it

**Comment by ai** [comment]
Sure, it is on you.

**Comment by ai** [comment]
@pekac another topic: we are thinking of adding some chat for developers. Do you have Telegram?

**Comment by pekac** [comment]
@ai yep, made it yesterday for this project :) 

Want me to ping you there?

**Comment by ai** [comment]
Yes, https://t.me/sitnik
