### ISSUE TITLE
Find `media` in Atom/RSS

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#60]
During parsing posts from RSS/Atom feed we need to parse all images in the text and put to `post.media` (list of URLs).

We will use them (don’t need to implement, just to understand why we need it):
1. To preload images for offline reading.
2. To render all images in post compact mode in feed.

**Comment by GreenTeaCake** [comment]
I want to take it

**Comment by ai** [comment]
Sure, it is your

**Comment by GreenTeaCake** [comment]
@ai RSS `item` can carry images not only inside `description` but in `media:content medium="image"` as well ([example](http://feeds.feedburner.com/blogspot/MKuf)). Should we get image URLs from the later ones too?

My proposal is to [get image links from all those sources ](https://github.com/hplush/slowreader/pull/123/files#diff-94a79126be0b16ed1a4c6dd9dd31779f8ceeaa243d03dc380190f4851ebc03c5R96) and [de-duplicate](https://github.com/hplush/slowreader/pull/123/files#diff-94a79126be0b16ed1a4c6dd9dd31779f8ceeaa243d03dc380190f4851ebc03c5R140).

**Comment by ai** [comment]
> My proposal is to [get image links from all those sources ](https://github.com/hplush/slowreader/pull/123/files#diff-94a79126be0b16ed1a4c6dd9dd31779f8ceeaa243d03dc380190f4851ebc03c5R96)and [de-duplicate](https://github.com/hplush/slowreader/pull/123/files#diff-94a79126be0b16ed1a4c6dd9dd31779f8ceeaa243d03dc380190f4851ebc03c5R140).

I like the idea.

Thanks for going deeper and thinking about reduplication 👍
