### ISSUE TITLE
Add JSON feed loader

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#8]
We need to define loader and test for JSON feed format.

We should re-use as much code as possible between RSS/Atom/JSON loaders.

https://en.wikipedia.org/wiki/JSON_Feed

**Comment by upteran** [comment]
Can I take this one ?

**Comment by ai** [comment]
Sure!

**Comment by upteran** [comment]
I encountered some cases during testing and want to clarify behavior.

## Current behavior
- Input URL of a webpage that has different kinds of RSS links (e.g., https://timetable.manton.org/).




![Image](https://github.com/hplush/slowreader/assets/12436035/c6cd61ad-63cc-4ecb-a995-1415a379f4cc)



- After the page is requested, each loader requests its own links and retrieves them.
- As a result, we get pages with `feedjson` and `rss` content.
- In the preview result list block, we can see a few items with the same name and content (one JSON, two rss+xml).


![Image](https://github.com/hplush/slowreader/assets/12436035/fe831523-6c63-4631-984d-a342d98d3712)


Probably, when we call `getLinksFromText` in the preview and request all links, we add all responses to the result list. In the case where we load different content of one feed type, it's okay, but when we have different types with the same content, it looks like duplication. Is this correct behavior, or we should do something with it ?

**Comment by ai** [comment]
> In the case where we load different content of one feed type, it's okay, but when we have different types with the same content, it looks like duplication. Is this correct behavior, or we should do something with it ?

It is OK if user will see RSS, Atom, and FeedJSON feeds together.

It is a little confusing, but we will think about it later. Right now most of RSS readers shows all feeds and advanced users expect it.
