### ISSUE TITLE
Improve semantic of navbar progress

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#86]
We have SVG with post uploading progress in menu.

![Captura desde 2024-03-18 22-49-02](https://github.com/hplush/slowreader/assets/19343/cb5ad6f1-8ef9-4164-bd58-b25749c35f49)

Unfortunately, it is not very accessible from screen readers because it has no semantics about the current progress.

1. We need to add semantics [using this guide](https://piccalil.li/blog/solution-009-progress-indicator/).
2. It will be good to double-check in other a11y guides.

**Comment by nbbrdn** [comment]
I want to take it

**Comment by ai** [comment]
@nbbrdn I moved task back to Onboarding. You still can create a PR, but the task is not locked to you now.

**Comment by AnnaGolmakova** [comment]
I'd like to take this one

**Comment by ai** [comment]
It is yours!

**Comment by AnnaGolmakova** [comment]
I've created a pull request
