### ISSUE TITLE
Add icon for development

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#93]
We should change app favicon for `localhost` and `dev.slowreader.app` to separate dev environment with production.

1. For dev environments we need to create separated versions of SVG icons. We don’t need to duplicate ICO icon.
2. We need to keep light/dark mode `<style>` hack in new icons.
3. Fire on the icons should be with the same yellow color.
4. For development let’s use [campfire](https://pictogrammers.com/library/mdi/icon/campfire/) icon.

**Comment by frkam** [comment]
I want to take it
