### ISSUE TITLE
Add mobile version of navbar

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#94]
We need to add mobile layout to the web client. In this task we will start from `<Navbar>`.

- [ ] By default, hide feeds/settings list. Make menu just like a line.
![Captura desde 2024-03-22 01-45-17](https://github.com/hplush/slowreader/assets/19343/198c8fa6-db22-4e16-ba09-865773ed31bb)
- [ ] Move it to the bottom of the screen for mobile and tablets
- [ ] Make it float over content. Be sure that the page has padding on the bottom, so bottom page’s content will not be hidden by floating menu.
- [ ] Show feeds/settings list above the menu when user click on Slow/Fast/Menu items.
- [ ] Hide feeds/settings list when user selects an item there.
- [ ] Think about tablet menu design.
- [ ] Add mobile/tablet stories to the Storybook.
- [ ] Check that settings page looks good. Ignore pages with `<TwoStepsPage>` for now.

**Comment by AnnaGolmakova** [comment]
I'd like to take it

**Comment by ai** [comment]
Sure. The task in on you.

**Comment by ai** [comment]
@AnnaGolmakova I moved task back to Onboarding. You still can create a PR, but the task is not locked to you now.

**Comment by AnnaGolmakova** [comment]
I haven't made it on time but I still decided to finish it. I would be happy to have a feedback if possible
