### ISSUE TITLE
Add mobile support to `<TwoStepsPage>` and Back button to mobile navbar 

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#95]
`<TwoStepsPage>` is used to show list on the left and selected list item on the right.

For instance, we use it in [feeds page](http://localhost:5173/feeds/categories) with feeds list on the left and selected feed on the right. On in the slow/fast feed with posts list on the left and selected post on the right.

On the phone we can’t show 2 sides, so we need to show only one side (list first and item when we chose it).

- [ ] Add a way to detect what side we need to show. We can use router for that. For instance, we can add `backRoutes[routeName] => (currentRoute) => backRoute` object.
- [ ] Think about some global API in `core` with what side is showed. We will need it in `<Navbar>` next. For instance, `backRoutes[route.get().route]`
- [ ] Add back button to Navbar which will show the list side back. You should replace Refresh icon with Back button when item’s side is shown. 
- [ ] It will be nice to add <kbd>Esc</kbd> support and to switch from item side to list side on pressing <kbd>Esc</kbd>.
- [ ] The same Exit button for desktop to the `<TwoSidePage>` (to the top of right panel).
- [ ] Add stories to test it and unit tests to `core` changes.
- [ ] Try to move to `core` as much as possible since we may need the same logic in React Native client later.

We also need to think about scroll position on list—item switching.

The task is blocked by https://github.com/hplush/slowreader/issues/94

**Comment by ilyatitovich** [comment]
I want to take it
