### ISSUE TITLE
Add loader tests on OPML file

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#96]
We need a way to test that loaders are working on real websites.

The tool will test loaders by:
1. Developer open their RSS reader and save all subscriptions to OPML file
2. Then the developer run our script and pass the path to that OPML file
3. This script takes every RSS feed from OPML file and test that it could parse it and find it from website home

To finish the task:

- [ ] Add `loader-tests/` project to monorepo.
- [ ] Create `README.md` and example a little.
- [ ] Add project description to the main `README.md`
- [ ] Add script. Import `@slowreader/core` and call `setEnvrionment()` with Node.js APIs.
- [ ] Add npm script to call that script to main `package.json`. Document it in main `README.md`.
- [ ] Read arguments. Show help on no file in argument. Show nice errors if we can’t read file.
- [ ] Parse OPML and get list of RSS URLs.
- [ ] For each RSS try to find the right loader by calling `loader.isMineText()`. Show nice error if the loader was not found.
- [ ] For found loader call `loader.getMineLinksFromText()`. Be sure that it returned some posts.
- [ ] For URL remove path (`https://example.com/news.rss` → `https://example.com/`) and call use methods from `core/preview.ts` to be sure that reader will find that RSS URL from the home. If URL was not found show warning (not error, since sometimes RSS link is hidden).
- [ ] Add to `CONTRIBUTION.md` to `How to Find Next Task` step to use this tool if you have RSS reader.

Use colors output by `picocolors`. You can use `nanospinner` for loading spinner.

**Comment by pekac** [comment]
I'd like to take this one, if it's ok?

**Comment by ai** [comment]
Thanks. This task blocks some other, so your help here will be very useful.
