### ISSUE TITLE
Add Markdown linter

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#97]
We need a linter to test Markdown files for:

1. That TOC has right titles and URLs.
2. That all links is alive.
3. That titles have the correct word's capitalization (`a`/`the` is small, noun is starting from big latter).
4. That file use curvy typography `"`→`”`, `'`→`’`.

To finish the task:
- [ ] Research for good Markdown linter. It should be able to check everything we need, be flexible and [use minimum size in node_modules](https://packagephobia.com/).
- [ ] Add `test:markdown` script to main `package.json`. So this script will be called on `pnpm test`.
- [ ] Find way to avoid calling in `.github/workflows/root.yml`.
- [ ] Add `.github/workflows/docs.yml` to run it on `**/*.md` files changes. 
- [ ] Check how fast it is. If it is very fast, add it to `nano-staged.json`.

**Comment by ilyatitovich** [comment]
I want to take it
