### ISSUE TITLE
Scroll page above on Next page click

### ISSUE THREAD

**Issue by ai** [hplush/slowreader#98]
On Fast posts page we have pagination and `Show next` button.

Now, after clicking on the button, page keeps scroll on the button of the page.

We need to fix it and scroll to top.

**Comment by sanchopanda** [comment]
I want to take it

**Comment by sanchopanda** [comment]
@ai I don't see the problem described. After clicking show next, scroll to the beginning of the feed https://monosnap.com/file/pE0u69zAycMun9GOhBTkbpu0kReSL1. Maybe I misunderstood the task?

**Comment by ai** [comment]
Try to use another button “Mark as read …”

**Comment by sanchopanda** [comment]
@ai At first I tried to implement it differently, i save it in [another branch](https://github.com/hplush/slowreader/compare/main...sanchopanda:slowreader:slowreader-98v2).  I  [assigned a link to an element to a key](https://github.com/hplush/slowreader/compare/main...sanchopanda:slowreader:slowreader-98v2#diff-53eedf36eb41eeda8138e6cad6ac43334af1bd2855ea068cb28bc228b833b432R12:~:text=setElement(%27stepOneElement%27%2C%20stepOne)) and [calling scrolling on the element by key directly in core/fast](elements.stepOneElement.scrollTo), but then I changed it to just dispatching event in window.

**Comment by sanchopanda** [comment]
> @ai At first I tried to implement it differently, i saved it in [another branch](https://github.com/hplush/slowreader/compare/main...sanchopanda:slowreader:slowreader-98v2). I [assigned a link to an element to a key](https://github.com/hplush/slowreader/compare/main...sanchopanda:slowreader:slowreader-98v2#diff-53eedf36eb41eeda8138e6cad6ac43334af1bd2855ea068cb28bc228b833b432R12:~:text=setElement(%27stepOneElement%27%2C%20stepOne)) and [calling scrolling on the element by key directly in core/fast](https://github.com/hplush/slowreader/compare/main...sanchopanda:slowreader:slowreader-98v2#diff-53eedf36eb41eeda8138e6cad6ac43334af1bd2855ea068cb28bc228b833b432R12:~:text=elements.stepOneElement.scrollTo), but then I changed it to just dispatching event in window.

I already read the comments, forget it)

**Comment by ai** [comment]
I just tried to read posts in https://dev.slowreader.app and scroll doesn’t work :(

**Comment by sanchopanda** [comment]
Ok, i'll take a look a look

**Comment by sanchopanda** [comment]
@ai  I couldn't reproduce the problem, can you please describe it in more detail?
https://monosnap.com/file/8KYyy6pYu7C9DNuS3jzmHszgXpq8iZ

**Comment by ai** [comment]
1. I used Firefox
2. I run local version of app (with the latest commit)
3. After I clicked on `Mark as read and next load` it was not scrolled.
4. When I open DevTools to reduce height (to make video smaller), the scroll started to work
5. When I moved DevTools on the side, it stops working

Can you try Firefox? Maybe it is just browser related?
